<h3>Maven</h3>
Documentation for the One-JAR Maven Plugin is available <a href="http://code.google.com/p/onejar-maven-plugin/">here</a>.
The plugin is pretty simple to use, but is lacking some more of the advanced features of the
Ant taskdef, namely ability to control manifest entries, and somewhat restricted by the Maven2
programming model of Jar dependencies.  I hope to extend it with these capabilities in the near
future.

<p/>The recommended release of this plugin is 1.4.4 or later, which corresponds to 0.97-RC11 of One-JAR
(released 7/14/2019).