<h2>One-JAR Open-Source License</h2>
The One-JAR license is a BSD-style license.  Compliance with this license is assured by including
the <a href="one-jar-license.txt">one-jar-license.txt</a> file in the One-JAR archive.  Both the 
Ant and Maven2 build tools do this automatically, putting this file in a "doc" directory in the
archive, and any separate documentation (e.g. as an Appendix).

<?php include("one-jar-license.html"); ?>

