<h2>Professional Support</h2>
One-JAR is Open-Source: it is licensed without guarantee or support but with full access to the source code.
If this proves insufficient, you can obtain professional consulting services on a contract basis by 
sending an email request to <i>one-jar-support(@)simontuffs.com</i> (remove the parentheses -- there is no spam-blocker
on this address for now, and I hope to leave it that way).

<p>We will be able to assist you in building and diagnosing your application, using remote
consulting methods including Skype, Email, Instant Messaging and Remote Desktop debugging sessions 
(VNC, Citrix Metaframe, etc.).  

<ul>
<li>Fast, efficent problem solving.</li>
<li>Extensive experience in building and diagnosing systems with the One-JAR classloading mechanisms.
<li>Over 20 years professional experience in the field of software development.</li>
</ul>

<p>Most problems only take a few hours to solve: you will save money by contracting with us. 
We know that you will be satisfied with our work, and can provide references from 
satisfied customers on previous contracts.

