<h2>Support</h2>
One-JAR is an Open-Source project, and comes without Support or Warranty.  The Open-Source project
is hosted on <a href="http://www.sourceforge.net/projects/one-jar">SourceForge</a> and there are
Bug Tracking and Feature Request Forums available at that site through the <a href="https://sourceforge.net/tracker/?group_id=111153">Tracker</a> capability.

<h2>Consulting Services</h2>
<p/>Efficient and effective professional consulting 
services are available from the author at competitive rates.  Please contact <img src="consulting.jpg" height="20" align="top"/>
if you would like to obtain consulting services.