<h2>Acknowledgements</h2>

Thanks to the following contributors for their suggestions and patches towards improving One-JAR:

<ul>
  <li>Christopher Ottley &amp; Dennis Pfisterer: The native library loading mechanism</li>
  <li>Erik Pragt: for sharing his Comic Reader application and working through a nasty recursion problem</li>
  <li>Geoff Bourne: Cleaning up the one-jar "myName" mechanism and improving cross-platform support.</li>
  <li>Alex Gadenz: Improving the URL handler with Mime-Type and anchor support</li>
  <li>Uwe Reimann: Cleaning up the source base for Java 5</li>
  <li>Nick Vincent: getting me to implement the META-INF/services mechanism properly</li>
  <li>Andreas Goetz: finding a problem with getPackage()</li>
  <li>Efrain Klein: for suggesting improvements to the argument parsing</li>
  <li>Oleg Astakhov: for pointing out that my documentation was inadequate, and suggesting improvements to it and the code</li>
  <li>Ferenc Hechler: for integrating One-JAR into Fat Jar and Eclipse (<a href="http://fjep.sourceforge.net">http://fjep.sourceforge.net</a>)
  <li>Everyone else for using it and providing feedback</li>
</ul>

Please forgive me if I've missed your name from this list, let me know and I'll be happy to acknowledge
your contributions!