<h2>Junit Test Suite</h2>

This page shows the JUnit test results from the One-JAR project.  We are at a 100% pass rate.
The test suite covers many aspects of the One-JAR classloading process, as well as the Ant
task creation.  Many of the test cases were created in response to bug reports, hence represent
comprehensive regression testing.
<p>This report was created using the <code>test</code> task in the <code>build.xml</code> file
at the top-level of the one-jar source tree, available from SourceForge's CVS.
<br/><br/>
<iframe src="documents/junit-noframes.html" width="100%" height="600"/>

