<h2>Source Code</h2>
The released source-code for One-JAR is contained in the bootstrap and example JAR files.  Simply unjar them
and you can be sure that the source is synchronized with the actual class files.

<h3>CVS</h3>
The CVS repository for One-JAR is located at SourceForge.  The CVS project is set up to work
with Eclipse 3.2.1.  The credentials for access are:

<pre>
    :pserver:anonymous@one-jar.cvs.sourceforge.net:/cvsroot/one-jar
</pre>

Note: the above information is subject to change: the definitive guide to access is
the One-JAR SourceForge CVS page: 

<pre>
    <a href="http://sourceforge.net/cvs/?group_id=111153">http://sourceforge.net/cvs/?group_id=111153</a>.
</pre>

<p>Web-based viewing access is available here: 

<pre>
    <a href="http://one-jar.cvs.sourceforge.net/one-jar/one-jar/">http://one-jar.cvs.sourceforge.net/one-jar/one-jar/</a>
</pre>
